
version: '3.6'

services:
  streamserver:
    image: skolar/live-streamserver
    build:
      context: streamserver
    ports:
      - 1935:1935

  website:
    image: skolar/live-website
    build:
      context: website

networks:
  default:
    external:
      name: skolar-livestream

