
version: '3.6'

services:
  streamserver:
    image: skolar/live-streamserver
    build:
      context: streamserver
    ports:
      - 1935:1935
      - 8081:80

  website:
    image: skolar/live-website
    build:
      context: website
    ports:
      - 8080:8080


